codecov:
  # we build and upload only a single coverage file, so we don't need to wait for other CI
  # jobs to complete for us to see the coverage results
  require_ci_to_pass: false

# not interested in inline PR comments via github checks
github_checks: false

comment:
  layout: "diff,files"

ignore:
  - "config/gen/**/*"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        only_pulls: true
        threshold: 0%
